name: Deploy React Portfolio

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Determine environment and set variables
        id: set-env
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "production" || "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
            echo "HOST=${{ secrets.REMOTE_HOST }}" >> $GITHUB_ENV
            echo "USER=${{ secrets.REMOTE_USER }}" >> $GITHUB_ENV
            echo "TARGET_PATH=${{ secrets.REMOTE_PATH }}" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
            echo "HOST=${{ secrets.REMOTE_HOST_STAGING }}" >> $GITHUB_ENV
            echo "USER=${{ secrets.REMOTE_USER_STAGING }}" >> $GITHUB_ENV
            echo "TARGET_PATH=${{ secrets.REMOTE_PATH_STAGING }}" >> $GITHUB_ENV
          fi

      - name: Debug environment variables
        run: |
          echo "Deploying to $DEPLOY_ENV"
          echo "Host: $HOST"
          echo "User: $USER"
          echo "Path: $TARGET_PATH"

      - name: Setup SSH manually
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -avz --delete dist/ "$USER@$HOST:$TARGET_PATH"
          echo "✅ Deployed to $DEPLOY_ENV"
