name: Deploy React Portfolio

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

# Required GitHub Secrets:
# - SSH_PRIVATE_KEY: Private SSH key for deployment
# - REMOTE_HOST: Production server hostname or IP
# - REMOTE_USER: Production server SSH username
# - REMOTE_PATH: Production server deployment path
# - REMOTE_HOST_STAGING: Staging server hostname or IP
# - REMOTE_USER_STAGING: Staging server SSH username
# - REMOTE_PATH_STAGING: Staging server deployment path

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Build project
        run: npm run build
        
        
      - name: Deploy to production (main branch)
        if: github.ref == 'refs/heads/main'
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_PATH }}
          
      - name: Deploy to staging (dev branch)
        if: github.ref == 'refs/heads/dev'
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_STAGING }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_STAGING }}
          TARGET: ${{ secrets.REMOTE_PATH_STAGING }}
          
      - name: Notify deployment status
        run: |
          echo "Deployment completed successfully!"
          echo "Deployed to: ${GITHUB_REF##*/} environment"
