name: Deploy React Portfolio

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

        
      - name: Create .env file
        run: |
          echo "VITE_EMAILJS_PUBLICKEY=${{ secrets.EMAILJS_PUBLICKEY }}" >> .env
          echo "VITE_EMAILJS_TEMPLATEID=${{ secrets.EMAILJS_TEMPLATEID }}" >> .env
          echo "VITE_EMAILJS_SERVICEID=${{ secrets.EMAILJS_SERVICEID }}" >> .env
          echo "VITE_EMAILJS_EMAIL=${{ secrets.EMAILJS_EMAIL }}" >> .env

      - name: Build project
        run: npm run build

      - name: Set production environment variables
        run: |
          echo "DEPLOY_ENV=production" >> $GITHUB_ENV
          echo "HOST=${{ secrets.REMOTE_HOST }}" >> $GITHUB_ENV
          echo "USER=${{ secrets.REMOTE_USER }}" >> $GITHUB_ENV
          echo "TARGET_PATH=${{ secrets.REMOTE_PATH }}" >> $GITHUB_ENV

      - name: Debug environment variables
        run: |
          echo "Deploying to $DEPLOY_ENV"
          echo "Host: $HOST"
          echo "User: $USER"
          echo "Path: $TARGET_PATH"

      - name: Setup SSH manually
        run: |
          echo "HOST is: $HOST"
          if [ -z "$HOST" ]; then
            echo "❌ HOST environment variable is empty. Exiting."
            exit 1
          fi
  
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
  
          echo "✅ SSH setup complete"

      - name: Deploy via rsync
        run: |
          rsync -e "ssh -p 21098 -o StrictHostKeyChecking=no" -avz --delete dist/ "$USER@$HOST:$TARGET_PATH"

       
